[[plugins]]
repo = 'vim-denops/denops.vim'
hook_add = '''
let g:denops_server_addr = '127.0.0.1:32123'
'''

[[plugins]]
repo = 'skanehira/denops-silicon.vim'
depends = ['denops.vim']
on_cmd = 'Silicon'
